### ISSUE TITLE
How to remove the reserved space left and right of SliderValueHorizontal

### ISSUE THREAD

**Issue by ZXHHYJ** [krottv/compose-sliders#1]
That is, to fill its width

**Comment by krottv** [comment]
Hi @ZXHHYJ 
Currently there's a reserved space which is thumbWidth / 2.
It was created to prevent thumb to go out of the view bounds. 
In order to modify it - you need to change the code.

**Comment by ZXHHYJ** [comment]
thanks, I have found a solution
